### ISSUE TITLE
Split 'Slide' into 3 axies

### ISSUE THREAD

**Issue by waylow** [waylow/boneWidget#2]
Markus is working on splitting the 'slide' function into the 3 axies.

It can be discussed here. (if need be)

**Comment by thenewcoder** [comment]
@waylow So, here's my first issue comment test.

I converted the FloatProperty to a FloatVectorProperty and had to fiddle around with the properties. This is what it looks like now:
```
 slide: FloatVectorProperty(
        name="Slide",
        default=(0.0, 0.0, 0.0),
        subtype='XYZ',
        unit='NONE',
        precision=1,
        description="Slide widget along xyz axes"
    )
```
It basically works now and will slide the widget along the bones xyz axes.

And what about the the proposed simple-advanced switch for the slide? Something you consider vital for now or can be added later?

**Comment by thenewcoder** [comment]
Seems like I've implemented the simple-advanced checkbox toggle. It will show the original version by default, but by checking the checkbox you get access to all 3 xyz axes.

I know this issue is for the slide thing, but what about for scale as well? I've implemented it, but can remove it if you don't want it.

**Comment by waylow** [comment]
are these changes in your repo?
How do I check it out - sounds spot on though.

**Comment by thenewcoder** [comment]
I'll push it to my repo. I did some other changes too. Or I can just make a pull request.

**Comment by thenewcoder** [comment]
It should be uploaded now on my repo. Take a look, and if it's OK and no other changes needed, I'll go ahead and make a pull request.

**Comment by waylow** [comment]
It's awesome dude.
can you make a pull request please?
I'm still a noob when it comes to git but I did manage to add your branch to my local repo (via the remote add)
But I can't get VSCodium to see your branch - Thankfully Blender does so I can at least test your changes.

One thing I have implemented recently was a change to the way the bone matrices are calculated.
It used to ignore and transformation the user made to the "Custom Object"
![Screenshot from 2024-06-09 21-48-37](https://github.com/waylow/boneWidget/assets/6591121/0de36cdc-e7dd-4023-a56d-1790d276112e)
If I merge this into my develop branch I should be able to get it working

**Comment by thenewcoder** [comment]
Done! And you seem to have been quite busy too.  :)
And I'm not much better with git or github for that matter.

**Comment by waylow** [comment]
Thanks man - merged
