### ISSUE TITLE
Preview Images For User Added Widgets

### ISSUE THREAD

**Issue by will-v-c** [waylow/boneWidget#9]
_(This is more of a request than an issue btw)_

Love the functionality of being able to add my own custom widgets! Gives me so much freedom as a user and makes my designer heart very happy. However, whenever I add a widget to the library, there isn't a preview image that goes along with it. I know it would likely be too much to ask for automatic image generation upon adding new widgets as you would have to have some way of snapshotting the widget which can be buggy when someone tries to add widgets with super dense meshes or issues with having the widgets not align with the camera.

HOWEVER, one simple workaround that I think would be awesome is adding in the option for users to customize the image of a widget manually but letting them actually upload an image. For me this would be a god send because I plan on designing custom widgets in Adobe Illustrator and importing those SVG's into Blender as curves which I then would convert to meshes before adding them to the widget library. I could then just export a low res png from Illustrator of the exact widget I made in there and be able to use that for the icon in the menu! Big win for usability, design, and customization

(oh also if y'all could somehow add the type to search functionality we have with the modifier panel/in the node editors, that would be awesome!).

Love this addon. You rock!

**Comment by waylow** [comment]
Hi Will, 
Thanks for your comments.

I think you'll be happy to hear that we are working on those features at the moment.  Well, they are planned anyway.
The first implementation will be the ability to add your own images before we do the harder thing of generating the previews automatically.

I'll mention the search thing to Markus (who implemented the popup menu)
